services:
  dashboard:
    build: dashboard
    networks:
      playground-net:
        # same as fyp/gatus
        ipv4_address: 172.20.0.50
        aliases:
          - dashboard

networks:
  playground-net:
    external: true
